services:

  hosteltool-nginx:
    build:
      context: .
      dockerfile: ./build/hosteltool-nginx.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      #- ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - hosteltool-php

  hosteltool-php:
    image: php:7-fpm
    volumes:
      - ./app:/app