services:
  hosteltool:
    build:
      context: .
    ports:
      - 8080:80
      - 9001:9001
    volumes:
      - ./app:/app
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/data/supervisord/supervisord.conf:/etc/supervisord.conf:ro
